### ISSUE TITLE
Azure Portal shows a new fourth object for all my agents now, an "SQL Virtual Machine".

### ISSUE THREAD

**Issue by tfabris** [JetBrains/teamcity-azure-agent#120]
## Description

My Team City agents (all of them are built with the Azure Plugin), when viewed in the Microsoft Azure Portal, now all have corresponding "SQL Virtual Machine" instances which I did not create. These have never been there before, and I'm not sure when they started appearing since it's been a while since I looked in the Azure Portal. In the past, my agent machines were always three objects: The VM, the Network Interface, and the OS disk drive. Now there is a fourth object, an "SQL Virtual Machine" that I never saw before. Is there any chance that Azure Plugin created these without my knowledge?

See screen shot attached, below.

## Environment

* Windows server 2016
* TeamCity version: 2019.2.1
* Azure plugin version:  0.8.7

## Diagnostic logs

I'm not seeing any mention of SQL in teamcity-clouds.log. I can arrange to privately send you any logs you need.

## Screen Shot

![image](https://user-images.githubusercontent.com/21208153/74294811-e589d200-4cf3-11ea-94f0-83f5e3179a64.png)

**Comment by burnasheva** [comment]
Hi @tfabris.
Could you please create a bug report in [YouTrack](https://youtrack.jetbrains.com/issues/TW) and attach screenshots with your cloud integration settings and teamcity-server.log and teamcity-clouds.log. Please, make all files visible only to the teamcity-developers group.
We need this information because I do not see this problem in my test account, so it isn't something known or common.

**Comment by tfabris** [comment]
Done, as requested:

**Comment by tfabris** [comment]
I'm closing the issue here and we can follow it on YouTrack. I think this might be a non-issue.
