### ISSUE TITLE
Diagnose build agents problems

### ISSUE THREAD

**Issue by tom-dudley** [JetBrains/teamcity-azure-agent#73]
I'd like to able to diagnose an issue I'm having on one of my agents so have started it manually from the Azure portal. Unfortunately it immediately shuts down with the logs showing:
```
Terminating instance AzureCloudInstance{myName='foo'}, profile 'bar'{id=arm-1} with idle time 1,112 minutes (idle time is 30 minutes)
```

I'm assuming the plugin only resets the idle time when it itself starts a VM. I have a few proposals for this:

1. Notice when the VM is started externally, reset the idle time to zero as soon at the plugin notices. (Or possibly work out how long the machine has been idle based on when it started)
2. Notice when the VM is started externally, and don't apply the timeout to this machine.
3. Notice when the VM is started externally, and apply some _other_ (user-configurable) timeout.

This second scenario would be very useful in the case where you have a build which only fails on a build agent, and requires investigation - which might be a lengthy process. This scenario puts the deallocation of the machine entirely in the hands of whoever manually started it.

The third scenario would be a guard against starting a machine manually for some reason, and then forgetting to deallocate it. As an example, the idle timeout might be 30 minutes whereas the 'other' timeout might be 4 hours (since it's not expected someone would not need to be on an agent for more than 4 hours).

Since in my case we have both cloud and local agents, and do investigations on agents which take longer than the timeout, I'd be in favour of the second or third suggestion.

**Comment by dtretyakov** [comment]
@tom-dudley, it's a quite complex task to store the state with a list of started cloud instances by cloud profile. Because we need to somehow store it and invalidate between TeamCity server restarts and cloud profile enabling/disabling events.

As a workaround you could temporary disable cloud profile to prevent azure integration control of this machine.

**Comment by tom-dudley** [comment]
I've been having a think about this and I think the best way to obtain the 'owner' of the VM would be to get the log event of the last `Microsoft.Compute/virtualMachines/start/action` operation and then compare the `Claims.Content.appid` against the `Application ID` known by the plugin. If they match then the owner is Teamcity, if they don't then the owner is someone else.

I imagine something akin to
```
public void Poll()
{
    string pluginApplicationId = GetPluginApplicationId();
    string owner = GetOwner();
    if (idleTime > timeoutPeriod && owner == pluginApplicationId)
        ShutdownAgent();
}

private string GetOwner()
{
    var lastStartEvent = GetLastStartEvent();
    return lastStartEvent.Claims.Content.AppId;
}
```

The only downside to this I can see would be if the application ID being used isn't solely used by Teamcity. I don't see why a dedicated Teamcity application couldn't be used though.

**Comment by tom-dudley** [comment]
As a further suggestion for solving this use case, I think having a "disable auto-shutdown" button per cloud agent would be suitable.

The workflow would then be:
- Notice a build failing on a specific agent which you want to investigate
- Disable the auto-shutdown
- Go and spend a couple of hours investigating on the agent
- Solve the problem
- Re-enable auto-shutdown

Optionally:
The "_other_" timeout mentioned in my initial post would kick in if that last `Re-enable auto-shutdown` step wasn't done.

**Comment by tfabris** [comment]
I am also having this issue.

Here are the steps I took, and which bit me this morning:

- I am having a problem with one particular agent according to Team City logs, and I want to investigate that particular agent.
- At the time I wanted to diagnose it, the agent had gone idle and has been shut down by the cloud plugin.
- I go into Team City administration page for the Cloud Agent plugin, and I set the idle time to "90" minutes.
- The Cloud Agents page on Team City does not give me a button to start that *particular* agent, so instead, I log into Azure and I start the agent there.
- In the Team City agents screen, the agent appears in the "Unauthorized" tab. 
- I set the agent to "Disabled" so that it doesn't pick up any new jobs which would interrupt my debugging session,, then I authorize the agent so I can begin doing experiments with it.
- While I am connected to the agent's remote desktop, before I have a chance to do anything at all, I get booted out of the remote desktop and the agent gets DELETED from Azure by the TeamCityCloudProfile account. (I confirmed this by looking at azure event history.)

@dtretyakov , What is the correct procedure for debugging a specific agent machine so that it does not get shut down or deleted while I am trying to debug it? 

Being able to diagnose and debug problems on an agent machine is critically important when you have complex systems of builds, unit tests, and integration tests running on cloud agents. Many times a failure will manifest itself only on a particular agent, and learning the root cause often requires long periods of time spent directly working on the faulty agent.

**Comment by dtretyakov** [comment]
@tfabris, at the moment proper way to do that is following:
* disable azure cloud profile without agents termination
* temporary disable required build agent for investigation
* return settings back

After changing idle time setting Azure Cloud integration will recycle all build agents with different settings while agent start/stop procedure and it was the cause of this vm deletion.

**Comment by tfabris** [comment]
@dtretyakov, thanks so much for that information!

If I disable the Azure cloud profile, though, doesn't that mean that no new cloud agents will get activated if the build/test load increases? Meaning that we will not get many/any new builds or tests launched while the debugging is happening on that one investigation machine? If that's true then this is a non-optimal way to handle this situation.

Imagine a situation like in our company, where there are hundreds of builds and integration tests launched in Team City per day. At any given time we have anywhere from 0-50 test agents running builds and tests in our Azure cloud, all of them managed by the plugin. Sometimes we want to investigate a problem on just one of those machines without affecting the rest of them. If the current running count is low, say, 2, and we have to do the investigation at that time, but then a new batch of builds and tests is launched, then the number of agents can't increase past that number of 2 and our queue stalls badly.

Are there plans to make this more optimal?

Thanks!

**Comment by dtretyakov** [comment]
Sorry for delay with supporting this use case. I've added a new wiki page describing possible ways to investigate problems with cloud build agents: https://github.com/JetBrains/teamcity-azure-agent/wiki/Problems-Investigation

To use mentioned ways please [update Azure plugin](https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support) to the version 0.8.3+.

@tom-dudley, @tfabris, please let me know if it covers your use cases completely.

**Comment by tom-dudley** [comment]
@dtretyakov Thanks for addressing this. One thing I would say is that the permissions to tag a VM may not always align with Teamcity permissions. Would it be possible to add a UI element either on the Agent Cloud tab, or the agent page itself which would perform the tagging/untagging? Perhaps a checkbox with text 'Investigation in progress' or 'Disable auto-shutdown'.

I appreciate if user A has checked the box then you probably don't want user B able to uncheck the box, but I imagine in that case that the checked would be visible to user B, but disabled, with a comment by it such as 'Currently being investigated by user A'.

**Comment by tfabris** [comment]
@dtretyakov , thank you so very much! This is excellent news and I'm excited to try it out.

One question: Tags on VMs in Azure are done as Key/Value pairs. When you tag the machine with “teamcity-investigation”, is that the key name, or is it the value? And if it's the key name, what must the value be? Can you clarify that in the Wiki entry?

Thanks!

**Comment by dtretyakov** [comment]
@tfabris, thanks for pointing it. `teamcity-investigation` is a tag key, you could use it with any value:
https://github.com/JetBrains/teamcity-azure-agent/wiki/Problems-Investigation#software-problems-on-cloud-build-agents

**Comment by tfabris** [comment]
@dtretyakov, thank you so much for clarifying it and for updating the wiki page!

**Comment by tfabris** [comment]
@dtretyakov, We upgraded our plugin to version 0.8.3, and I'm trying to follow the instructions on the wiki, but it doesn't seem to be working as documented. After adding the tag "teamcity-investigation" with a value of "True" to the machine in Azure, the machine still gets shut down after 30 minutes of inactivity anyway, despite the tag having been set.

I also don't see any indication on any Team City screen that the machine is being treated in any particularly special way. 

For instance, if the machine is running, and its tag is set, I look in the Agents/Connected tab in Team City, the machine is still there. If I look in the Agents/Cloud tab in Team City, the machine shows in the list of agents as normal. If I select the agent and look at its Agent Summary tab, everything looks normal. If I look at its "Agent Parameters" tab, including the sub-tabs of System Properties, Environment Variables, and Configuration Parameters, I don't see anything related to this new tag.

I've even tried rebooting the agent machine to be sure, and I still don't see anything that's been made different by this tag. And the machine still shuts down after 30 minutes of inactivity.

So after adding the tag to the machine in Azure, where exactly, in the Team City screens, should I be looking to find that it's working as designed? And what troubleshooting steps should I do to help find out where things are going wrong?

Thanks!

**Comment by tom-dudley** [comment]
@tfabris I believe I'm seeing the same behaviour and have opened a support ticket with Jetbrains for the issue. Out of interest do you see any of following `INFO` lines in your `teamcity-clouds.log` file? (assuming your agent is called `agent`):

```
Terminating instance AzureCloudInstance{myName='agent'}, profile 'Azure'{id=arm-1} with idle time 10 minutes (idle time is 10 minutes)
Terminating instance: AzureCloudInstance{myName='agent'}, profile 'Azure'{id=arm-1}, reason: idle timeout of 10 minutes reached
Virtual machine agent is marked by teamcity-investigation tag
```

**Comment by tfabris** [comment]
@tom-dudley, @dtretyakov, thanks so much for your information about the log file. Here is an example of what I'm seeing in my log file. The system correctly logs the fact that the machine is marked by the tag, but then it decides to shut it down anyway. Here is a sample of the relevant log section.


```
[2018-05-23 11:05:25,118]   INFO [onPool-worker-0] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:06:28,152]   INFO [onPool-worker-2] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:07:32,094]   INFO [onPool-worker-1] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:08:37,227]   INFO [onPool-worker-0] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:09:41,241]   INFO [onPool-worker-7] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:10:40,682]   INFO [uled executor 5] - te.IdleTimeoutTerminateFactory - Will stop instance AzureCloudInstance{myName='hybrid40-19'}, profile 'Azure ARM'{id=arm-1, projectId=project122} with idle time 30 minutes (idle time is 30 minutes) 
[2018-05-23 11:10:40,683]   INFO [uled executor 5] - l.instances.StopInstanceAction - Terminating instance: AzureCloudInstance{myName='hybrid40-19'}, profile 'Azure ARM'{id=arm-1, projectId=project122}, reason: After 30 minutes idle 
[2018-05-23 11:10:40,683]   INFO [uled executor 5] - r.impl.DBCloudStateManagerImpl - Image: AzureCloudImage{myName='hybrid40-'}, profile: profile 'Azure ARM'{id=arm-1, projectId=project122} was marked to CONTAIN agent 
[2018-05-23 11:10:40,688]   INFO [uled executor 5] - uds.base.AbstractCloudInstance - Changing hybrid40-19(961190) status from Running to Scheduled to stop  
[2018-05-23 11:10:40,690]   INFO [onPool-worker-4] - ouds.azure.arm.AzureCloudImage - Stopping virtual machine hybrid40-19 
[2018-05-23 11:10:41,159]   INFO [uled executor 1] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to stop' state, profile 'Azure ARM'{id=arm-1, projectId=project122}, AzureCloudInstance{myName='hybrid40-19'} 
[2018-05-23 11:10:53,202]   INFO [onPool-worker-6] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:11:51,022]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent "hybrid40-19" {id=28312} because: Instance has been terminated. AzureCloudInstance{myName='hybrid40-19'}, profile 'Azure ARM'{id=arm-1, projectId=project122} 
[2018-05-23 11:11:51,043]   INFO [Ping Executor 1] - .server.impl.CloudEventsLogger - Cloud agent Unregistered agent "hybrid40-19" {id=28312} is no longer recognized as cloud agent because instance has gone: profileId=arm-1, imageId=hybrid40-, instanceId=hybrid40-19 
[2018-05-23 11:11:51,043]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent Unregistered agent "hybrid40-19" {id=28312} because: Cloud instance (id=hybrid40-19, imageId=hybrid40-, profileId=arm-1) has gone (is not reported by cloud profile) 
[2018-05-23 11:11:56,658]   INFO [onPool-worker-1] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:12:59,990]   INFO [onPool-worker-7] - onnector.AzureApiConnectorImpl - Virtual machine hybrid40-19 is marked by teamcity-investigation tag 
[2018-05-23 11:13:19,708]   INFO [onPool-worker-4] - uds.base.AbstractCloudInstance - Changing hybrid40-19(961190) status from Scheduled to stop to Stopped  
[2018-05-23 11:13:19,708]   INFO [onPool-worker-4] - ouds.azure.arm.AzureCloudImage - Virtual machine hybrid40-19 has been successfully terminated 
```

**Comment by tfabris** [comment]
@tom-dudley , @dtretyakov , any new word on this?

Does the log snippet that I just posted confirm that there is a bug?

**Comment by dtretyakov** [comment]
Sorry for delay, I'll investigate the problem, but it from the description it behaves not as expected.

**Comment by dtretyakov** [comment]
@tom-dudley, @tfabris, in the plugin version 0.8.4 I've tried to fix found problems. Please try upgrading to it: https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support

Now build agents marked by `teamcity-investigation` tag will be displayed as Stopped on Agent -> Cloud page.

**Comment by tfabris** [comment]
@dtretyakov, thank you so much! I will test this as soon as we get a chance to get our plugin upgraded, and report back.

**Comment by tfabris** [comment]
@dtretyakov, I'm testing this out with the following steps:
- Agent computer is running and is visible/connected in the "Agents" screen.
- I disable the agent in the "Agents" screen.
- I the Azure portal, I put the teamcity-investigation flag on that azure virtual machine of that agent computer.
- I notice that in the Cloud Agents screen, that agent indeed goes to a "stopped" state as you said that it would.
- I notice that in the Agents screen, the agent is still there and listed as "disabled".
- I am able to perform my investigations on that agent computer.
- So far so good.

Here are some unexpected things that I have encountered so far:
- When I look at the teamcity-clouds.log file, I no longer see messages related to the teamcity-investigation flag as I had seen before.
- If, as part of my investigations, if I need to reboot the agent machine (for example if I install software onto the agent which requires a reboot), then after the reboot is complete, I now see that the agent is listed as "Unauthorized" in team city and must now manually authorize it again.

Are those last two things expected to happen?

Thanks!

**Comment by tfabris** [comment]
@dtretyakov, one other thing to add to the list of unexpected things:

I am unable to assign Team City builds directly to the machine after going through the steps listed above, it says "there are no fully-running cloud agents" when I queue the build.

For example:
- Imagine that I'm having a build problem on one of the cloud agents and I need to investigate it.
- I set the agent to "disabled" in the Agents screen in Team City so that no new jobs get automatically queued on it while I investigate it.
- I add the teamcity-investigation flag to the agent in the Azure portal. This successfully prevents the machine from being shut down.
- I investigate the machine, I find the problem, I find the thing that I need to fix, and I fix it.
- The machine needs a reboot so I reboot it.
- The machine goes into "Unauthorized" status in the Agents screen (as described in my prior post) so I authorize it.
- After authorizing it, the machine goes into "Connected" in the Agents screen and I must disable it again to prevent other jobs from getting automatically queued to it.
- So far so good...

But now I have a specific job I want to queue to that agent, to make sure I really fixed the thing.
- I queue a job to run on that specific agent in Team City.
- Normally this works: Disabled agents don't pick up random jobs automatically, but I can choose to queue a job directly to a specific agent and it normally works.
- So far it looks like it's working but I notice that the job never actually runs.
- Look closer in the Team City queue and I see that this job is flagged as "there are no fully-running cloud agents", despite the fact that the agent is in the "Connected" screen and it's in the right project pool.
- Even if I re-enable the machine, it still says "there are no fully-running cloud agents".
- I have to remove the teamcity-investigation tag. Once I remove the teamcity-investigation tag, then the job works and can run on the machine.

I'm not sure if that's expected behavior or not. I can certainly work around it in this case since I know the behavior.

**Comment by dtretyakov** [comment]
@tfabris, thank you for such detailed explanation, will try to resolve these corner cases, but it could require some changes in TeamCity cloud core to fully support all of them.

**Comment by tfabris** [comment]
@dtretyakov , thank you so much. I am successfully using this feature now, and successfully working around the things I listed above.

I have documented the steps for our internal company employees as follows. Feel free to copy any of my language below for the Wiki entry if you like.

- Required version of Team City Azure Cloud Agent Plugin: version 0.8.4+ 
- In the Team City "Agents" screen, disable the machine so that it does not automatically pick up new jobs.
- In the Azure portal, add a new tag on the virtual machine. The tag must have the name of “teamcity-investigation”, and text in the value field can be any non-blank text.
- While this tag is active:
   - The machine will not get automatically shut down due to inactivity.
   - The machine will show as "Stopped" in the "Cloud" tab of the Team City "Agents" screen, even though it is running.
   - If you have to reboot the machine during your investigations, it will disappear from the "Connected" tab on Team City, and will eventually reappear in the "Unauthorized" tab instead. You will need to press the "Authorize" button in that tab and disable the machine again.
   - In some situations, you might be unable to queue new jobs directly onto the machine. The jobs will seem to get queued correctly, but the jobs will not run, and in the queue they will get flagged with the note "there are no fully-running cloud agents". Remove the tag, but leave the machine disabled, in order to queue new jobs directly onto the machine.
- When done investigating, make sure to delete the tag and re-enable the machine so that it is fully back into rotation with the other agents.

**Comment by tfabris** [comment]
Correction: A reboot of the agent machine is not required in order to make it disappear from the "Connected" tab and move to the "Unauthorized" tab. It happens on its own after a short while.

**Comment by dimyriy** [comment]
@tom-dudley Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61948 for updates.
